site_name: CodeOnTap Docs

repo_url: https://github.com/codeontap/codeontap/

theme: readthedocs

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav: 
  - 'Introduction': './README.md'
  - 'Getting Started' : 
    - 'Introduction' : './getting-started/README.md'
    - 'Local Environment Setup' : './getting-started/local-env-setup.md'
    - 'Create CMDB' : './getting-started/cmdb-setup.md'
    - 'Deploy Components' : './getting-started/deploy-components.md'
  - 'About' :
    - 'Release Process' : './about/versioning.md'