site_name: CodeOnTap
docs_dir: docs

repo_url: https://github.com/codeontap/codeontap/

theme: 
  name: readthedocs
  titles_only: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav: 
  - 'Introduction': './index.md'
  - 'Getting Started' : 
    - 'Introduction' : './getting-started/index.md'
    - 'Local Environment Setup' : './getting-started/local-env-setup.md'
    - 'Create CMDB' : './getting-started/cmdb-setup.md'
    - 'Deploy Basic Components' : './getting-started/deploy-basic-components.md'
    - 'Encrypt Secrets' : './getting-started/encrypt-secrets.md'
    - 'Deploy Product Components' : './getting-started/deploy-product-components.md'
    - 'Accessing Jenkins' : './getting-started/accessing-jenkins.md'
  - 'Developer Guides':
    - 'Introduction' : './developer-guides/index.md'
    - 'AWS Data Pipelines' : './developer-guides/aws-data-pipeline.md'
  - 'Reference' : 
    - 'Components' : './reference/component-reference.md'
  - 'Development' : 
    - 'Introduction' : './development/index.md'
    - 'Versioning' : './development/versioning.md'
    - 'Create a Release' : './development/creating-a-release.md'
    - 'Creating References' : './development/creating-references.md'