site_name: CodeOnTap
docs_dir: docs

repo_url: https://github.com/codeontap/codeontap/

theme: 
  name: readthedocs
  titles_only: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav: 
  - 'Introduction': './index.md'
  - 'Getting Started' : 
    - 'Introduction' : './getting-started/index.md'
    - 'Local Environment Setup' : './getting-started/local-env-setup.md'
    - 'Create CMDB' : './getting-started/cmdb-setup.md'
    - 'Deploy Basic Components' : './getting-started/deploy-basic-components.md'
    - 'Encrypt Secrets' : './getting-started/encrypt-secrets.md'
    - 'Deploy Product Components' : './getting-started/deploy-product-components.md'
    - 'Accessing Jenkins' : './getting-started/accessing-jenkins.md'
  - 'Developer Guides':
    - 'Introduction' : './developer-guides/index.md'
    - 'AWS Data Pipelines' : './developer-guides/aws-data-pipeline.md'
  - 'Release Management':
    - 'Introduction' : './release-management/index.md'
  - 'Reference' : 
    - 'Components' : './reference/component-reference.md'
    - 'Configuration Management Database' : './reference/cmdb-reference.md'
  - 'Release Notes' :
    - '5.5' : '.change-logs/5.5.md'
    - '6.0' : '.change-logs/6.0.md'
  - 'Advanced' : 
    - 'Introduction' : './advanced/index.md'
    - 'Versioning' : './advanced/versioning.md'
    - 'Create a Release' : './advanced/creating-a-release.md'
    - 'Creating References' : './advanced/creating-references.md'