site_name: CodeOnTap
docs_dir: docs

repo_url: https://github.com/codeontap/codeontap/

theme: 
  name: readthedocs
  titles_only: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav: 
  - 'Introduction': './index.md'
  - 'Getting Started' : 
    - 'Introduction' : './getting-started/index.md'
    - 'Local Environment Setup' : './getting-started/local-env-setup.md'
    - 'Create CMDB' : './getting-started/cmdb-setup.md'
    - 'Deploy Components' : './getting-started/deploy-components.md'
  - 'About' :
    - 'Release Process' : './about/versioning.md'
  - 'Reference' : 
    - 'Components' : './reference/component-reference.md'